# This file was generated by GoReleaser. DO NOT EDIT.
cask "kinder" do
  version "1.6"

  on_macos do
    on_intel do
      sha256 "b3afd5de3e003145fdc30f88e0cde682952c1d83db4d463e885a3e2b78690299"
      url "https://github.com/PatrykQuantumNomad/kinder/releases/download/v#{version}/kinder_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a8d58fc30a8a94896c7af0c0af22c60d93e43753ce942e3826599332afeae0b"
      url "https://github.com/PatrykQuantumNomad/kinder/releases/download/v#{version}/kinder_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2b1c206273707ca9952917c0c15a0a57c892cd6f5dabada53473541f8018343e"
      url "https://github.com/PatrykQuantumNomad/kinder/releases/download/v#{version}/kinder_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "13a550b4a3233e508630328ac56deb91d49952ee7b9b5dee84c2b1dc54fef2aa"
      url "https://github.com/PatrykQuantumNomad/kinder/releases/download/v#{version}/kinder_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kinder"
  desc "kind, but with everything you actually need."
  homepage "https://kinder.patrykgolabek.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kinder"

  # No zap stanza required

end
