# This file was generated by GoReleaser. DO NOT EDIT.
cask "kinder" do
  name "kinder"
  desc "kind, but with everything you actually need."
  homepage "https://kinder.patrykgolabek.dev"
  version "1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kinder"

  on_macos do
    on_intel do
      url "https://github.com/PatrykQuantumNomad/kinder/releases/download/v#{version}/kinder_#{version}_darwin_amd64.tar.gz"
      sha256 "866253bd2c0c72e2d6561382ecdd63063ef200a885f3907ad290edba87cec9b0"
    end
    on_arm do
      url "https://github.com/PatrykQuantumNomad/kinder/releases/download/v#{version}/kinder_#{version}_darwin_arm64.tar.gz"
      sha256 "09a3c4283e6252e005cbfa227fb3d83b4776aeb605ff29895b3c3167563f81da"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/PatrykQuantumNomad/kinder/releases/download/v#{version}/kinder_#{version}_linux_amd64.tar.gz"
      sha256 "27b6a115df1e4b48894541ba794abfca15592a9c0244d66ae3a0ed853c573f5f"
    end
    on_arm do
      url "https://github.com/PatrykQuantumNomad/kinder/releases/download/v#{version}/kinder_#{version}_linux_arm64.tar.gz"
      sha256 "cc6b1f72c09ea1a1f066751a85713e171c2de72f15235f1d3690d00b105571a6"
    end
  end

  # No zap stanza required
end
