# This file was generated by GoReleaser. DO NOT EDIT.
cask "kinder" do
  version "1.4"

  on_macos do
    on_intel do
      url "https://github.com/PatrykQuantumNomad/kinder/releases/download/v#{version}/kinder_#{version}_darwin_amd64.tar.gz"
      sha256 "b6d5e33c3481943f7a907fb5f651db756d2151bc6df86c994c637ffe534f63eb"
    end
    on_arm do
      url "https://github.com/PatrykQuantumNomad/kinder/releases/download/v#{version}/kinder_#{version}_darwin_arm64.tar.gz"
      sha256 "245efe16e7430c6efb84d968bd48b1afd8e601f1762bf7fe9a36fa817cc53de3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/PatrykQuantumNomad/kinder/releases/download/v#{version}/kinder_#{version}_linux_amd64.tar.gz"
      sha256 "a2001438288fee10c102611f3944024a1e73d7dd798523fc0dc5b4288d718651"
    end
    on_arm do
      url "https://github.com/PatrykQuantumNomad/kinder/releases/download/v#{version}/kinder_#{version}_linux_arm64.tar.gz"
      sha256 "a7169fde5ffff86206bab6ff4477286ddcf7967e5971158415b8d3fe89bb2168"
    end
  end

  name "kinder"
  desc "kind, but with everything you actually need."
  homepage "https://kinder.patrykgolabek.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kinder"

  # No zap stanza required

end
